### ISSUE TITLE
Exception when calling ApiAuthApi->login: (404)

### ISSUE THREAD

**Issue by Lathesh-B-L** [bufferapp/lookerpy#7]
When try to run the below example code to verify the connectivity 

import time
import lookerpy
from lookerpy.rest import ApiException
from pprint import pprint
    # create an instance of the API class
api_instance = lookerpy.ApiAuthApi()
client_id = 'client_id' # client_id provided as per the API3 Key.
client_secret = 'client_secret' # client_secret provided as per the API3 Key.

try:
    # login
    api_response = api_instance.login(client_id=client_id, client_secret=client_secret)
    pprint(api_response)
except ApiException as e:
    print ("Exception when calling ApiAuthApi->login: %s\n" % e)

got the exception "Exception when calling ApiAuthApi->login: (404)"

Exception when calling ApiAuthApi->login: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json;charset=utf-8', 'Vary': 'Accept-Encoding', 'X-Content-Type-Options': 'nosniff', 'Content-Length': '69', 'Connection': 'keep-alive'})
HTTP response body: {"message":"Not found","documentation_url":"http://docs.looker.com/"}

Please suggest.

**Comment by davidgasquez** [comment]
Hey there @Lathesh-B-L! We generated this `lookerpy` package some time ago and haven't updated it. I think the Looker API has changed and is not compatible anymore. We should mark this repository as deprecated.

 I'll try to solve https://github.com/bufferapp/pylooker/issues/7 though!
